name: importar redes.json para supabase

on:
  workflow_dispatch:

jobs:
  etl-json-para-supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: pip install psycopg[binary]
      - name: Importar redes.json
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python import_redes_json.py
